services:
  policy-management-frontend:
    build: policy-management-frontend
    image: lakesidemutual/policy-management-frontend
    environment:
      - "VUE_APP_POLICY_MANAGEMENT_BACKEND=http://localhost:8085"
    ports:
      - "3010:80"

  customer-management-frontend:
    build: customer-management-frontend
    image: lakesidemutual/customer-management-frontend
    depends_on:
      - policy-management-frontend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=http://localhost:8085"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://localhost:8085/customer-management"
      - "REACT_APP_POLICY_MANAGEMENT_FRONTEND=http://localhost:3010"
    ports:
      - "3020:80"

  customer-self-service-frontend:
    build: customer-self-service-frontend
    image: lakesidemutual/customer-self-service-frontend
    depends_on:
      - policy-management-frontend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=http://localhost:8085"
      - "REACT_APP_POLICY_MANAGEMENT_BACKEND=http://localhost:8085"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://localhost:8085/customer-management"
    ports:
      - "3000:80"
