# ----------------- JMS Queue Names -----------------
insuranceQuoteRequestEvent.queueName=insurance-quote-request-event-queue
customerDecisionEvent.queueName=customer-decision-event-queue
insuranceQuoteResponseEvent.queueName=insurance-quote-response-event-queue
insuranceQuoteExpiredEvent.queueName=insurance-quote-expired-event-queue
policyCreatedEvent.queueName=policy-created-event-queue

# ----------------- Security / Tokens -----------------
token.header=X-Auth-Token
token.expiration=604800

# ----------------- Rate Limiting -----------------
rate.limit.perMinute=60

# ----------------- API Key (if still used) -----------------
apikey.header=Authorization
apikey.value=b318ad736c6c844b

# ----------------- App -----------------
spring.application.name=customer-self-service-backend

spring.jackson.serialization.INDENT_OUTPUT=true
spring.jackson.default-property-inclusion=NON_NULL

# added to make circuit breaker support work:
spring.main.allow-bean-definition-overriding=true

# Optional (only if you run Spring Boot Admin locally)
# spring.boot.admin.client.url=http://localhost:9000
